### ISSUE TITLE
(AsyncTcpListener).RunAsync() causes System.NotSupportedException

### ISSUE THREAD

**Issue by wontonhonkon** [ygoe/AsyncTcpClient#1]
http://prntscr.com/km4mtd

**Comment by ygoe** [comment]
Can you please tell me more about what you're doing there? Especially the .NET framework and version would be interesting. This has so far only been tested with .NET Core 2.0/2.1 on Windows 10.

**Comment by ygoe** [comment]
Not reproducible. This code works with .NET Core 2.1 and .NET Framework on Windows 10.1709, .1803 and Windows 7.
