### ISSUE TITLE
How to send message from server to all connected clients?

### ISSUE THREAD

**Issue by badalexander** [ygoe/AsyncTcpClient#11]
First of all I want to congratulate you on the excellent code.
I have a problem. How to implement sending a message from the server to all connected clients. I've tried to debug to understand but I'm a little lost
Thank you,
Alex

**Comment by serious-angel** [comment]
Appending code might help ^^

**Comment by badalexander** [comment]
Discovered how to do it :)
you need to add a ConcurrentDictionary of all the connected clients in your  code for example in RunAsync2
In ConnectedCallback add each serverClient to the ConcurrentDictionary 
Add ClosedCallback action to ClientConnectedCallback
In ClosedCallback function remove the serverClient from the ConcurrentDictionary 

And add a function to iterate over all the members of the ConcurrentDictionary and send a message.
![image](https://user-images.githubusercontent.com/77934269/109955267-f801ef80-7cea-11eb-9dff-5c59aa0a1bb0.png)

Pretty easy

**Comment by ygoe** [comment]
Yes, that sounds plausible.
