### ISSUE TITLE
AsyncTcpClient.Dispose()  causes "Network error: Software caused connection abort" when using PuTTY

### ISSUE THREAD

**Issue by FS-JuLi** [ygoe/AsyncTcpClient#2]
I added your classes to my code and have to say: nice work. But i had a little issue with AsyncTcpClient:

My Environment:
1. I start the AsyncTcpClient by using your example code of RunAsync2() of your demo application
2. I only added "serverClient.Dispose();" as last line inside the ReceivedCallback, because I want the listener to close the connection after the reply was sent.

User Problem:
When using PuTTY to test the communication, the "serverClient.Dispose()" causes PuTTY to complain about a lost connection (Message Box "Network error: Software caused connection abort").

Code Problem:
When calling AsyncTcpClient.Dispose(), the underlying socket gets forcefully terminated without properly diconnecting it.

Solution:
Instead of 
`tcpClient?.Dispose();`
use
````
if (tcpClient != null){
    if (tcpClient.Client != null){
        tcpClient.Client.Disconnect(false);
    }
    tcpClient.Close();
    tcpClient.Dispose();
}
````
Best Regards

Arnothar

**Comment by ygoe** [comment]
Thank you for the info. I have tried it myself and could reproduce the connection reset. Furthermore, there were `ObjectDisposedExceptions` when it was time to stop the server.

I have now added a `Disconnect` method to the `AsyncTcpClient` class to properly close the connection without tearing too many things down prematurely. The demo now shows how to disconnect from either the client side (when entering an empty message) or from the server side (when the message "bye" was received). Now I get no connection reset from PuTTY and no exceptions when the server is stopped after its timeout.

Please review my changes and let me know if this improves the situation for you, so I can release a new version of the package.

**Comment by FS-JuLi** [comment]
Thank you for letting me know that you updated your project.

Unfortunately, I am currently unable to test the current changes as I am working on another urgent project.
But as soon as I find some time, I'll like to look at it.
