### ISSUE TITLE
How to send the same data from Server to ALL clients?

### ISSUE THREAD

**Issue by mikihiro-t** [ygoe/AsyncTcpClient#6]
Thank you for your AsyncTcpClient Solution.  It's very useful.

I'd like to send the same data from Server to ALL clients.
For example, in a window of Server App, Click Button then, send the same data to all connected clients. No needs ReceivedCallback.
I have tried to add AsyncTcpClient Classes to list , but I could not do it.
Could you help me?

**Comment by ygoe** [comment]
I can't do much without seeing your code.
